In [1]:
import pickle

In [2]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [3]:
X

array([[[ 36,  30,  64, ...,  49,  54,  45],
        [ 37,  32,  61, ...,  49,  43,  43],
        [ 36,  35,  60, ...,  48,  47,  45],
        ...,
        [ 94,  29,  36, ...,  39,  48,  45],
        [ 29,  15,  22, ...,  32,  42,  47],
        [ 19,  14,  14, ...,  31,  40,  47]],

       [[173, 172, 173, ...,  83,  87,  84],
        [172, 172, 171, ...,  78,  76,  84],
        [171, 170, 171, ...,  95,  90,  86],
        ...,
        [  4,   4,   9, ...,  53,  63,  75],
        [  2,   5,   3, ...,  58,  52,  68],
        [  6,   7,   7, ...,  61,  64,  62]],

       [[ 45,  47,  47, ...,  43,  41,  37],
        [ 45,  47,  47, ...,  43,  43,  42],
        [ 45,  47,  47, ...,  43,  43,  42],
        ...,
        [212, 213, 213, ..., 176, 172, 172],
        [205, 198, 205, ..., 175, 177, 174],
        [208, 211, 213, ..., 168, 168, 169]],

       ...,

       [[ 15,  48,  82, ...,  40,  24,   5],
        [  6,  55,  79, ...,  38,  17,   6],
        [  7,  48,  75, ...,  33,  23,  11

In [4]:
y

array([0, 0, 0, ..., 0, 1, 0])

In [5]:
X = X/255

In [9]:
X

array([[[0.65882353, 0.65098039, 0.65098039, ..., 0.45098039,
         0.42745098, 0.40392157],
        [0.65490196, 0.65098039, 0.65098039, ..., 0.45098039,
         0.42745098, 0.40784314],
        [0.65490196, 0.65490196, 0.65490196, ..., 0.45490196,
         0.43137255, 0.40784314],
        ...,
        [0.69019608, 0.70588235, 0.7254902 , ..., 0.39607843,
         0.39607843, 0.39607843],
        [0.68627451, 0.6745098 , 0.6745098 , ..., 0.39215686,
         0.39607843, 0.39607843],
        [0.69803922, 0.70588235, 0.73333333, ..., 0.39607843,
         0.39215686, 0.39607843]],

       [[0.34901961, 0.35686275, 0.36470588, ..., 0.23529412,
         0.23137255, 0.21176471],
        [0.34901961, 0.36078431, 0.37647059, ..., 0.22745098,
         0.21960784, 0.21960784],
        [0.34901961, 0.36078431, 0.37647059, ..., 0.21568627,
         0.21176471, 0.22745098],
        ...,
        [0.43137255, 0.42352941, 0.39607843, ..., 0.49019608,
         0.47058824, 0.43921569],
        [0.3

In [6]:
X = X.reshape(-1, 60, 60, 1)

In [7]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [8]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [9]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             multiple                  640       
                                                                 
 max_pooling2d (MaxPooling2D  multiple                 0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           multiple                  36928     
                                                                 
 max_pooling2d_1 (MaxPooling  multiple                 0         
 2D)                                                             
                                                                 
 flatten (Flatten)           multiple                  0         
                                                                 
 dense (Dense)               multiple                  1

In [ ]:
model.fit(X, y, epochs=5, validation_split=0.1)

In [23]:
X.shape

(23000, 60, 60, 1)

In [27]:
import time

time.time()

1581428129.5990093

In [28]:
type(1581428129.5990093)

float

In [10]:
X_test = pickle.load(open('X_test.pkl', 'rb'))
y_test = pickle.load(open('y_test.pkl', 'rb'))

In [26]:
X_test = X_test/255
X_test = X_test.reshape(-1, 60, 60, 1)